// 30 kalimat pujian/lucu bagi orang yang menalangi paling banyak
// Impor di Step 3, ambil secara acak, lalu tampilkan bersama nama teman

export const praiseWords = [
  "Wadidaw, dompetmu tebal banget! Thanks udah traktir segunung!",
  "Gokil! Kamu ATM berjalan hari ini, salut!",
  "Sultan mode ON – semuanya kenyang karena kamu!",
  "Dompetmu power bank, nggak pernah lowbat. Terima kasih, bos!",
  "Wow, si paling royal! Kita jadi terselamatkan dari dompet kering.",
  "Kamu baiknya kebangetan, bisa bikin kantin tutup lebih cepat!",
  "Mantap jiwa, traktiranmu bikin mood semua naik level!",
  "Si paling dermawan, saldo e‑wallet kami ikutan senyum!",
  "Legend! Sekali gesek langsung semua lunas.",
  "Pahlawan dompet sejati, restu jajan selalu menyertaimu!",
  "Sumpah, kamu cocok jadi duta cashback nasional.",
  "Traktirannya bikin perut kenyang dan hati senang!",
  "Santuy banget bayarin, dompet kita auto holiday.",
  "Epic! Kamu bikin tanggal muda terasa sepanjang bulan.",
  "Dewa patungan telah turun tangan, thanks banget!",
  "Kece parah – saldo minus kami berubah jadi senyuman.",
  "Influencer kebaikan: satu swipe, semua happy!",
  "Kamu kaya buku tabungan: selalu menenangkan hati.",
  "Hoki kita hari ini = ketemu kamu yang royalnya maksimal!",
  "Level generous kamu: over 9000!",
  "Traktiranmu bak sinar matahari di akhir bulan gelap.",
  "Bestie, saldo kamu unlimited apa gimana? Respect!",
  "Dompet kamu tahan banting, kita yang senang!",
  "Tiap kamu bayar, malaikat cashback menari‑nari.",
  "Cuan splash! Semua berkat dirimu, master budget.",
  "Berkah jajan menetes deras dari tanganmu.",
  "Kalau kebaikan punya bentuk, ya dompetmu itu!",
  "Makan enak terjamin kalau ada kamu di grup!",
  "Niat traktirnya bikin kami terharu plus kenyang.",
  "Thanks! Kamu bikin kita auto hemat sampai gajian.",
  "Sachet sedekahmu jumbo banget, bikin kita kenyang sampe besok!",
  "Kalau royal ada liga, kamu juara Champions!",
  "Swipe‑mu seperti hujan THR, syahdu di akhir bulan.",
  "Dompetmu sekeras Vibranium, menangkis rasa lapar kami!",
  "Kebaikanmu bikin yang ngirit jadi malu.",
  "Sakti! Sekali tap, semua tagihan lenyap.",
  "ATM hidup detected – terima kasih, majikan!",
  "Saldo kamu kok kayak cheat code, nggak habis‑habis.",
  "Berkatmu, perut kami berdendang dangdut bahagia.",
  "You rock! Kopi gratis rasanya seperti libur nasional.",
  "Royalti level dewa, sampai kasir pun terharu.",
  "Kamu ngetraktir, bumi terasa lebih damai.",
  "Saldo kami menipis, kamu muncul sebagai pahlawan.",
  "Is this magic? Tagihan hilang seketika!",
  "Denganmu, tanggal tua berubah jadi flash sale.",
  "Dompetmu bak taman hiburan, banyak wahana cashback.",
  "Kebaikanmu bikin BMI dompet kami kembali ideal.",
  "Gajian siapa? Yang penting ada kamu!",
  "Tolong, NASA tolong teliti dompet supermassive ini!",
  "Kamu laksana oase di gurun tanggal tua.",
  "Traktiranmu setara 100 emoji 🔥!",
  "Boros sih, tapi demi orang lain, mulia banget.",
  "Harta, tahta, traktiran kamu.",
  "Kamu mematahkan hukum kekekalan saldo.",
  "Nggak heran kasir tadi senyum terus.",
  "Skill paylater manusia tapi limit dewa.",
  "Dermawan mode infinity stone activated.",
  "Masukkan kode: BAGIBAGI – oh, itu kamu!",
  "Porsi kebaikanmu jumbo super mantap.",
  "Kita makan enak, diet dompetmu yang kena.",
  "Kebaikanmu bikin alarm keuangan kami snooze.",
  "Jika kebaikan adalah saham, kamu blue chip‑nya.",
  "Saldo minus? Tenang, ada kamu plus!",
  "Dompet kami berdansa salsa, thanks to you.",
  "Tingkat generosity‑mu bikin Santa minder.",
  "Setiap swipe‑mu, bunga lotus mekar di neraca.",
  "Kamu sponsor resmi kebahagiaan perut.",
  "Lebih cepat dari kilat: tagihan lunas!",
  "Tiket surga diskon 50% karena ketulusanmu.",
  "Influencer finansial positif nomor satu!",
  "Kalau royal itu seni, kamu Picasso‑nya.",
  "Budget planner kami pensiun dini karenamu.",
  "Dompetmu bak pita Möbius, nggak ada ujungnya.",
  "Terima kasih telah menyelamatkan akhir bulan kami.",
  "Kebaikanmu bikin ATM kehabisan struk.",
  "Wallet flex kamu bikin kardus Indomie cemburu.",
  "Kamu definisi walking blessing.",
  "Top up pahala full bar!",
  "Bukti nyata 'sharing is caring'.",
  "Saldo kamu setebal plot twist drama Korea.",
  "Tanpa kamu, tagihan itu masih horor.",
  "Berkatmu, kami auto upgrade mood ke VIP.",
  "Traktiran legenda, bakal dikenang sampai lebaran.",
  "Keuangan kamu 24/7 on fire demi teman.",
  "Kaum mendang‑mending langsung terbungkam.",
  "Kebaikanmu anti ghosting, selalu hadir.",
  "Cash flow kamu sihir level Hogwarts.",
  "Swipe kartu seperti menabuh genderang kemenangan.",
  "Dompetmu weightlifting tagihan berat.",
  "Royalty vibes unlimited edition.",
  "Tanpa minyak, kamu sudah bikin ekonomi bergerak.",
  "Kami jadi penikmat, kamu jadi legenda.",
  "Thank you for saving our snack lives.",
  "Kebaikanmu bukan kaleng‑kaleng, ini drum band.",
  "Your generosity broke the scale!",
  "Kalau kebaikan dibeli, kamu grosirnya.",
  "Tagihan kami lari terbirit‑birit melihatmu.",
  "Traktiranmu = plot armor kita di tanggal tua.",
  "Saat kantong krisis, kamu hadir bak Avengers!",
  "Ulala! Barista kagum, kita pun makmur.",
  "Saldo kamu orbitnya jauh di atas gaji kami.",
  "Keajaiban pembayaran instan, courtesy of you!",
  "Dompetmu bak charger 100W: cepat & powerful.",
  "Neraca keuanganmu bikin Wall Street iri.",
  "Setiap traktir, dopamine saya auto full.",
  "Kebaikanmu bikin KPI bahagia tercapai.",
  "Bisikan dompetmu: 'relax guys, gua cover'.",
  "Senyum kasir jadi bukti dompetmu super hero.",
  "Kamu bukan sekadar teman; kamu investor kebahagiaan.",
  "Traktiranmu bikin spreadsheet pengeluaran kita libur.",
  "Dompetmu stamina dewa, ga kenal lelah.",
  "Royal level sultan kripto bull run.",
  "Berkat kamu, perut kenyang, hati senang, saldo aman!",
];

// Contoh pemakaian:
// const pujian = praiseWords[Math.floor(Math.random() * praiseWords.length)];
